---
- name: Ensure the k3s config directory exists
  become: true
  ansible.builtin.file:
    path: "/etc/rancher/k3s/"
    state: "directory"
    mode: "+x"
    
- name: Ensure remote bundle directory is created
  ansible.builtin.file:
    path: "{{ remote_bundles_dir }}"
    state: "directory"
    mode: "+x"

- name: Copy bundle
  ansible.builtin.copy:
    src: "{{ local_bundle_dir }}/"
    dest: "{{ remote_edge_bundle_dir }}"
    mode: "+x"

- name: Place the k3s binary at /usr/local/bin/k3s and ensure it is executable
  become: true
  ansible.builtin.copy:
    src: "{{ remote_edge_bundle_dir }}/k3s"
    dest: "/usr/local/bin/k3s"
    remote_src: true
    mode: "+x"

- name: Ensure the k3s images directory exists
  become: true
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/agent/images/"
    state: "directory"
    mode: "+x"

- name: Place the images tar file in the images directory
  become: true
  ansible.builtin.unarchive:
    src: "{{ remote_edge_bundle_dir }}/k3s-airgap-images-amd64.tar.gz"
    dest: "/var/lib/rancher/k3s/agent/images/"
    remote_src: true

- name: Stop firewall service
  ansible.builtin.systemd:
    name: firewalld
    state: stopped