---
- name: Install first k3s control plane node
  hosts: first_master
  roles:
    - k3s-install-first-master

- name: Install other k3s control plane nodes
  hosts: other_masters
  roles:
    - k3s-install-other-masters

- name: Install k3s agent nodes
  hosts: workers
  roles:
    - k3s-install-agents
