---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd