---
- name: Copy k3s config file
  become: true
  template:
    src: ../templates/config.yaml
    dest: /etc/rancher/k3s/config.yaml
    mode: 0644

- name: Install K3s
  become: true
  shell:
    cmd: "INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server --server https://{{ hostvars['master01']['ansible_host'] }}:6443' ./install.sh"
    chdir: "{{ remote_edge_bundle_dir }}"
  ignore_errors: true
  async: 600
  poll: 5

# - name: Ensure k3s is running
#   become: true
#   ansible.builtin.systemd:
#     state: restarted
#     name: k3s

- name: Create .kube directory
  ansible.builtin.file:
    state: directory
    path: "/home/{{ ansible_user }}/.kube"

- name: Copy the kubeconfig to the .kube directory
  become: true
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    mode: 0644
