---
- debug:
    msg: "CPU Architecture {{ ansible_architecture }}"

- name: Create temporary local directory
  ansible.builtin.file:
    path: "{{ local_bundle_dir }}"
    state: directory
  delegate_to: localhost

- name: Create temporary local manifests directory
  ansible.builtin.file:
    path: "{{ local_bundle_manifests_dir }}"
    state: directory
  delegate_to: localhost

- name: Download k3s binary
  ansible.builtin.get_url:
    url: "{{ k3s_binary_url[ansible_architecture] }}"
    dest: "{{ local_bundle_dir }}/k3s"
    mode: "+x"

- name: Download k3s images
  ansible.builtin.get_url:
    url: "{{ k3s_airgap_images_url[ansible_architecture] }}"
    dest: "{{ local_bundle_dir }}/k3s-airgap-images.tar.gz"
    mode: "0644"

- name: Download k3s install script
  ansible.builtin.get_url:
    url: "{{ k3s_install_script }}"
    dest: "{{ local_bundle_dir }}/install.sh"
    mode: "+x"

- name: Move ArgoCD manifests to the local temporary bundled manifests directory
  ansible.builtin.copy:
    src: "../files/{{ item }}"
    dest: "{{ local_bundle_manifests_dir }}/"
  delegate_to: localhost
  with_items: 
    - "argo.yaml"
  when: components.argo is true

- name: Move Gitlab manifests to the local temporary bundled manifests directory
  ansible.builtin.copy:
    src: "../files/{{ item }}"
    dest: "{{ local_bundle_manifests_dir }}/"
  delegate_to: localhost
  with_items: 
    - "gitlab.yaml"
  when: components.gitlab is true

- name: Download rook manifests
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ local_bundle_manifests_dir }}/"
    mode: "0644"
  with_items: 
    - "{{ rook_crds_url }}"
    - "{{ rook_common_url }}"
    - "{{ rook_operator_url }}"
    - "{{ rook_cluster_url }}"
    - "{{ rook_toolbox_url }}"
  when: components.rook is true

- name: Archive the bundle and the Ansible playbooks
  ansible.builtin.archive:
    path: "{{ playbook_dir }}"
    dest: "{{ playbook_dir }}/../{{ bundle_name }}.tgz"
  delegate_to: localhost
